# Generated by Django 4.2.4 on 2024-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Fname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Lname',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
