# Generated by Django 4.2.4 on 2024-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_remove_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlogmodel',
            name='back_acc_no',
        ),
        migrations.RemoveField(
            model_name='transactionlogmodel',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='transactionlogmodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionlogmodel',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionlogmodel',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionlogmodel',
            name='trans_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
