# Generated by Django 4.2.4 on 2024-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_remove_transactionlogmodel_mem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogmodel',
            name='trans_id',
            field=models.CharField(max_length=100),
        ),
    ]
