# Generated by Django 4.2.4 on 2024-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_alter_investmentmodel_roi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='mf_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='stock_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='stock_price',
            field=models.IntegerField(),
        ),
    ]
