# Generated by Django 4.2.4 on 2024-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_alter_portfoliomodel_mf_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmodel',
            name='roi',
            field=models.IntegerField(),
        ),
    ]
