# Generated by Django 4.2.4 on 2024-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_alter_investmentmodel_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmodel',
            name='valuation',
            field=models.IntegerField(),
        ),
    ]
