# Generated by Django 4.2.4 on 2024-01-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_alter_investmentmodel_valuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesmodel',
            name='article',
        ),
        migrations.AddField(
            model_name='resourcesmodel',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resourcesmodel',
            name='books',
            field=models.CharField(default='', max_length=100),
        ),
    ]
