# Generated by Django 4.2.4 on 2023-09-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemonsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('height', models.IntegerField(null=True)),
                ('moves', models.CharField(max_length=20, null=True)),
                ('sprites', models.ImageField(null=True, upload_to='')),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
